courses/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^list/$',
        views.ManageCourseListView.as_view(),
        name="manage_course_list"),
    url(r'^create/$',
        views.CourseCreateView.as_view(),
        name="create_course"),
    url(r'^(?P<pk>\d+)/edit/$',
        views.CourseUpdateView.as_view(),
        name="edit_course"),
    url(r'^(?P<pk>\d+)/delete/$',
        views.CourseDeleteView.as_view(),
        name="delete_course"),
    url(r'^(?P<pk>\d+)/module/$',
        views.CourseModuleUpdateView.as_view(),
        name="update_course_module"),

    #url(r'^module/(?P<module_id>\d+)/content/(?P<model_name>\w+)/create/$',
    #    views.ContentCreateUpdateView.as_view(),
    #    name="create_module_content"),

    #url(r'^module/(?P<module_id>\d+)/content/(?P<model_name>\w+)/(?P<id>\d+)/$',
    #    views.ContentCreateUpdateView.as_view(),
    #    name="update_module_content"),


    # create lecture
    url(r'^module/(?P<module_id>\d+)/lecture/create/$',
        views.LectureCreateUpdateView.as_view(),
        name="create_lecture"),
    # update lecture
    url(r'module/(?P<module_id>\d+)/lecture/(?P<lecture_id>\d+)/$',
        views.LectureCreateUpdateView.as_view(),
        name="update_lecture"),
    # delete lecture
    url(r'lecture/(?P<lecture_id>\d+)/delete/$',
        views.LectureDeleteView.as_view(),
        name="delete_lecture"),
    # create lecture content
    url(r'^module/(?P<module_id>\d+)/lecture/(?P<lecture_id>\d+)/content/(?P<model_name>\w+)/create/$',
        views.ContentCreateUpdateView.as_view(),
        name="create_lecture_content"),
    # update lecture content
    url(r'^module/(?P<module_id>\d+)/lecture/(?P<lecture_id>\d+)/content/(?P<model_name>\w+)/(?P<id>\d+)/$',
        views.ContentCreateUpdateView.as_view(),
        name="update_lecture_content"),


    url(r'^content/(?P<id>\d+)/delete/$',
        views.ContentDeleteView.as_view(),
        name="delete_lecture_content"),
    url(r'^module/(?P<module_id>\d+)/$',
        views.ModuleLectureListView.as_view(),
        name="module_lecture_list"),
    url(r'^module/order/$',
        views.ModuleOrderView.as_view(),
        name="order_modules"),
    url(r'^content/order/$',
        views.ContentOrderView.as_view(),
        name="order_content"),

    url(r'^lecture/order/$',
        views.LectureOrderView.as_view(),
        name="order_lecture"),

    url(r'^subject/(?P<subject>[\w-]+)/$',
        views.CourseListView.as_view(),
        name="subject_course_list"),
    url(r'^(?P<slug>[\w-]+)/$',
        views.CourseDetailView.as_view(),
        name="course_detail"),


    #url(r'^module/(?P<module_id>\d+)/quiz/create/$',
    #    views.CreateQuizView.as_view(),
    #    name="create_quiz"),

    #url(r'^module/(?P<module_id>\d+)/quiz/(?P<pk>\d+)/$',
    #    views.UpdateQuizView.as_view(),
    #    name="update_quiz"),
]

diploma/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from rest_framework import routers
from courses.views import CourseListView, IndexView, LoginView, InstructorRegistrationView
from students.views import add
from students.forms import UsersLoginForm
from courses.viewsets import QuestionViewSet, LectureViewSet, ContentViewSet, QuestionList


router = routers.DefaultRouter()
router.register(r'questions', QuestionViewSet)
router.register(r'lectures', LectureViewSet)
router.register(r'contents', ContentViewSet)


urlpatterns = i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'accounts/login/$', LoginView.as_view(), name="login"),
    #url(r'^accounts/login/$', auth.login, {'authentication_form': UsersLoginForm}, name="login"),
    url(r'^accounts/logout/$', auth.logout, {'next_page': '/'}, name="logout"),
    url(r'^course/', include('courses.urls')),
    url(r'^courses/$', CourseListView.as_view(), name="course_list"),
    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^students/', include('students.urls')),

    # регистрация преподавателей
    url(r'^accounts/registration/$',
        InstructorRegistrationView.as_view(),
        name='instructor_registration'),

    # social auth
    url(r'^social/', include('social_django.urls', namespace='social')),
    # for nested_admin app
    url(r'^nested_admin/', include('nested_admin.urls')),
    # api urls
    url(r'api/', include(router.urls)),
    url(r'api1/(?P<ids>.+)/$', QuestionList.as_view()),

    # avatar
    url(r'^avatar/', include('avatar.urls')),
    # update avatar
    url(r'^avatar/add-or-update/$', add, name='add_update_avatar'),

    # for internationalization with rosetta
    url(r'^rosetta/', include('rosetta.urls')),
)

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

students/urls.py
from django.conf.urls import url
from django.views.decorators.cache import cache_page
from . import views

urlpatterns = [
    #регистрация студентов
    url(r'^registration/$',
        views.StudentRegistrationView.as_view(),
        name="student_registration"),

    # подписка студента на курс
    url(r'^enroll/$',
        views.StudentEnrollCourseView.as_view(),
        name="student_enroll_course"),

    # список курсов на которые подписан студент
    url(r'^courses/$',
        #cache_page(60 * 30)(views.StudentCourseListView.as_view()),
        views.StudentCourseListView.as_view(),
        name="student_course_list"),

    # содержание курса
    url(r'^courses/(?P<pk>\d+)/$',
        #cache_page(60 * 30)(views.StudentCourseDetailView.as_view()),
        views.StudentCourseDetailView.as_view(),
        name="student_course_detail"),

    #
    #url(r'courses/(?P<pk>\d+)/curriculum/$',
    #    views.course_curriculum,
    #    name="student_course_curriculum"),

    # about курса
    url(r'courses/(?P<pk>\d+)/about/$',
        views.course_about,
        name="student_course_about"),

    # отображение модуля курса
    url(r'^courses/(?P<pk>\d+)/modules/(?P<module_id>\d+)/$',
        #cache_page(60 * 30)(views.StudentCourseDetailView.as_view()),
        views.StudentCourseDetailView.as_view(),
        name="student_course_detail_module"),

    # лекция курса
    url(r'^courses/(?P<pk>\d+)/modules/(?P<module_id>\d+)/lectures/(?P<lecture_id>\d+)/$',
        #cache_page(60 * 30)(views.StudentCourseDetailView.as_view()),
        views.StudentCourseDetailView.as_view(),
        name="student_course_detail_module_lecture"),

    # изменения данных профиля студентов/преподавателей
    url(r'^profile/$',
        views.update_profile,
        name="update_profile"),

    # отображение контента лекций
    #url(r'^course/(?P<course_id>\d+)/(?P<pk>\d+)/(?P<lecture_id>\d+)/$',
    #    views.StudentModuleDetailView.as_view(),
    #    name="lecture_detail"),

    #url(r'module-detail/$',
    #    views.ModuleDetail.as_view(),
    #    name="detailed_module"),

    #url(r'lecture-detail/$',
    #    views.LectureDetail.as_view(),
    #    name="detailed_lecture"),

    # страница оповещающая об окончании курса
    url(r'course/completed/$',
        views.CourseCompleted.as_view(),
        name="course_completed"),
]

students/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name=_("Profile user"))
    date_of_birth = models.DateField(blank=True, null=True, verbose_name=_("Birthday date"))
    #photo = models.ImageField(upload_to='users_photo/%Y/%m/%d', blank=True)

    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)


# Сигналы будут выполнены, когда будет создан и сохранен экземпляр User модели ---
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()
# --------------------------------------------------------------------------------

students/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.utils.translation import ugettext_lazy as _
from courses.models import Course
from .models import Profile


class CourseEnrollForm(forms.Form):
    # при проверке формы заполняется одним
    # экземпляром объекта модели из queryset
    course = forms.ModelChoiceField(queryset=Course.objects.all(),
                                    widget=forms.HiddenInput)


class UsersLoginForm(AuthenticationForm):
    username = forms.CharField(
        label='',
        widget=forms.TextInput(
            attrs={'class': 'form-control form-group',
                   'placeholder': _('Username or Email Address'),
                   'required': 'True'}
        )
    )
    password = forms.CharField(
        label='',
        widget=forms.PasswordInput(
            attrs={'class': 'form-control form-group',
                   'placeholder': _('Password'),
                   'required': 'True'}
        )
    )


class UsersCreationForm(UserCreationForm):
    '''username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control form-group',
                   'placeholder': 'Username',
                   'required': 'True'}
        )
    )
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={'class': 'form-control form-group',
                   'placeholder': 'Email address',
                   'required': 'True'}
        )
    )'''
    password1 = forms.CharField(
        label='',
        widget=forms.PasswordInput(
            attrs={'class': 'form-control form-group',
                   'placeholder': _('Password'),
                   'required': 'True'}
        )
    )
    password2 = forms.CharField(
        label='',
        widget=forms.PasswordInput(
            attrs={'class': 'form-control form-group',
                   'placeholder': _('Confirm Password'),
                   'required': 'True'}
        )
    )

    class Meta:
        model = User
        fields = ('username', 'email',)
        widgets = {
            'username': forms.TextInput(
                    attrs={'class': 'form-control form-group',
                           'placeholder': _('Username'),
                           'required': 'True'}
            ),
            'email': forms.EmailInput(
            attrs={'class': 'form-control form-group',
                   'placeholder': _('Email Address'),
                   'required': 'True'}
            )
        }
        labels = {
          'username': '',
          'email': ''
        }
        help_texts = {
          'username': '',
        }


# форма для изменения некоторых данных из User модели
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')
        widgets = {
          'first_name': forms.TextInput(
                attrs={
                    'class': 'form-control form-group',
                    'placeholder': _('First name'),
                }
            ),
          'last_name': forms.TextInput(
                attrs={
                    'class': 'form-control form-group',
                    'placeholder': _('Last name')
                }
            ),
          'email': forms.EmailInput(
                attrs={
                    'class': 'form-control form-group',
                    'placeholder': _('Email'),
                    'required': 'True'
                }
            )
        }

# форма для изменения некоторых данных из Profile модели
class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth',)
        widgets = {
            'date_of_birth': forms.DateInput(
                attrs={
                    'class': 'form-control form-group',
                    'placeholder': _('Birthday date')
                }
            )
        }
        labels = {
            'date_of_birth': _("Birthday date")
        }

# не используется----------------------------------------------------------
class InstructorsCreationForm(UserCreationForm):
    password1 = forms.CharField(
        #label='Password',
        widget=forms.PasswordInput(
            attrs={'class': 'form-control form-group',
                   'placeholder': _('Password'),
                   'required': 'True'}
        )
    )
    password2 = forms.CharField(
        #label='Confirm password',
        widget=forms.PasswordInput(
            attrs={'class': 'form-control form-group',
                   'placeholder': _('Confirm password'),
                   'required': 'True'}
        )
    )
    '''group = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control form-group',
                   'placeholder': '',
                   'required': 'True',
                   'value': 'Instructor'}
        )
    )'''

    class Meta:
        model = User
        fields = ('username', 'email',)
        widgets = {
            'username': forms.TextInput(
                    attrs={'class': 'form-control form-group',
                           'placeholder': _('Username'),
                           'required': 'True'}
            ),
            'email': forms.EmailInput(
            attrs={'class': 'form-control form-group',
                   'placeholder': _('Email address'),
                   'required': 'True'}
            )
        }
        labels = {
            'username': _("Username"),
            'email': _('E-mail'),
            'password1': _('Password'),
            'password2': _('Confirm password')
        }
# ---------------------------------------------------------------------------

students/templates/students/student/edit_profile.html
{% extends "base.html" %}

{% load bootstrap %}

{% load avatar_tags %}

{% load staticfiles %}

{% load i18n %}

{% block title %}
    {% trans 'Profile' %}
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datepicker.min.css' %}">
{% endblock %}


{% block content %}
<div class="content">
    <h1>Edit profile</h1>
    <div class="row">
        <!-- <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3"> -->
        <div class="col-md-6 col-sm-6 col-xs-12">

            <div class="small-card small-card-body">

                <form action='.' method='POST'>
                    {{ user_form|bootstrap }}
                    {{ profile_form|bootstrap }}
                    <!--{{ user_form.first_name }}
                    {{ user_form.first_name.errors }}

                    {{ user_form.last_name }}
                    {{ user_form.last_name.errors }}

                    {{ user_form.email }}
                    {{ user_form.email.errors }}

                    {{ profile_form.date_of_birth }}
                    {{ profile_form.date_of_birth.errors }} -->
                    {% csrf_token %}
                    <p><button type='submit' class="btn btn-primary btn-hg btn-block">{% trans 'Save' %}</button></p>
                </form>

                <!-- {% if request.user|has_avatar %}
                {% avatar user 65 %}
                {% else %}
                <img src="{% static 'img/default_avatar.png' %}" width="65px">
                {% endif %}
                <a href="{% url 'avatar_change' %}">Change your avatar</a> -->

            </div>

        </div>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="small-card small-card-body">
                <p class="text-center"><strong>{% trans 'Your current avatar' %}</strong></p>
                <div class="flex-center zoomInUp animated">{% avatar user %}</div>

                <form enctype="multipart/form-data" method="POST" action="{% url 'add_update_avatar' %}">
                    <!-- {{ upload_avatar_form.as_p }} -->
                    <div class="flex-center">
                    <span class="btn btn-success fileinput-button">
                    {{ upload_avatar_form.avatar }}
                    </span>
                    </div>
                    {% csrf_token %}<input type="submit" class="btn btn-primary btn-hg btn-block" value="{% trans 'Update avatar' %}" />
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
<script type="text/javascript">
    $('#id_date_of_birth').datepicker({
        format: 'mm/dd/yyyy'
    })
</script>
{% endblock %}

students/templates/students/student/registration.html
{% extends "base.html" %}

{% load bootstrap %}

{% load i18n %}

{% block title %}
    {% trans 'Signup' %}
{% endblock %}

{% block content %}

<div class="content">
    <div class="row">
        <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 user-form">

                <h1 class="text-center">{% trans 'Student registration' %}</h1>
                <form action="." class="register-form" method="POST">
                    <!-- {{ form.username }}
                    {{ form.email }}
                    {{ form.password1 }}
                    {{ form.password2 }} -->
                    {{ form|bootstrap }}
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}" />
                    <input type="submit" class="btn btn-primary btn-hg btn-block" value="{% trans 'Register' %}" />
                </form>

                <hr class="login-hr">

                <div class="social-auth">
                    <a class="btn btn-hg fb-bg"
                       href="{% url 'social:begin' 'facebook' %}">
                            <i class="fa fa-facebook" aria-hidden="true"></i> FB
                    </a>
                    <a class="btn btn-hg g-bg"
                       href="{% url 'social:begin' 'google-oauth2' %}">
                            <i class="fa fa-google" aria-hidden="true"></i> Google
                    </a>
                    <a class="btn btn-hg vk-bg"
                       href="{% url 'social:begin' 'vk-oauth2' %}">
                            <i class="fa fa-vk" aria-hidden="true"></i> VK
                    </a>
                </div>

                <br>
                <p class="text-center">
                    {% trans 'Have account?' %}
                    <a href="{% url 'login' %}">
                        {% trans 'Log in now' %}
                    </a>
                </p>
        </div>
    </div>
</div>

{% endblock %}